### ISSUE TITLE
Release Workflow is missing Read Permissions

### ISSUE THREAD

**Issue by Finwood** [astral-sh/trusted-publishing-examples#1]
For a private repository, the release workflow is missing the `contents: read` permission:

https://github.com/astral-sh/trusted-publishing-examples/blob/24971e1aacf6277a711ae47c7d8a2dbd91f96aea/.github/workflows/release.yml#L17-L18

With the added permission, the workflow also works on private repos:

```yaml
jobs:
  pypi:
    permissions:
      contents: read
      id-token: write
```

_At least for me, but maybe I was missing something..._ 🤔
